# Site settings
title: Nicolas Hoizey, passionate about the Web and photography
author: Nicolas Hoizey
email: nicolas@hoizey.com
description: > # this means to ignore newlines until "baseurl:"
  Nicolas Hoizey, passionate about the Web and photography, among many other interests.
baseurl: ""
url: "https://nicolas-hoizey.com"
twitter_username: nhoizey
github_username: nhoizey

# Handling content with date in the future
future: false

# Markdown parsing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: "⬆︎"
  header_offset: 1

# Indexing for related post using the classifier-reborn plugin
lsi: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: "articles"
      type: "posts"
    values:
      layout: "post"
      lang: en
      categories:
        - articles
      permalink: :year/:month/:title.html
  - scope:
      path: "links"
      type: "posts"
    values:
      layout: "link"
      lang: en
      categories:
        - links
      permalink: :categories/:year/:month/:title.html

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags

exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - tags/spip.html
  - Rakefile
  - vendor
include:
  - .htaccess
  - .well-known
  - favicon.jpg
  - tags

# Jekyll Assets
assets:
  compression: true
  plugins:
    css: { autoprefixer: {} }
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 10"

# Get data from Notist
jekyll_get:
  data: talks
  json: "https://noti.st/nhoizey.json"

# POSSEify plugin settings
posseify:
  twitter:
    max_length: 280
    url_length: 23
    link:
      min_hashtags: 1
      max_hashtags: 5
      template: "&#128279; @posse_content<br>\n@posse_url<br>\n<br>\n@posse_tags"
    post:
      min_hashtags: 3
      max_hashtags: 5
      template: "@posse_title\n\n@posse_url\n\n@posse_tags"

# Algolia
algolia:
  application_id: …
  index_name: …
  read_only_api_key: …
  nodes_to_index: "p,li,figcaption,blockquote"
  files_to_exclude:
    - 404.html
    - index.html
    - search.html
    - offline.html
    - offline-fallback.html
    - about/mentions.html
    - tags/index.html
    - links/index.html
    - tools/*

# Webmention
webmentions:
  # debug: true
  username: nicolas-hoizey.com
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  pause_lookups: false
  collections:
    - links
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  js: false
  legacy_domains:
    - http://nicolas-hoizey.com
  throttle_lookups:
    #   last_week: daily
    last_month: daily
    last_year: weekly
    older: every 2 weeks

# YouTube
youtube:
  api_key: …

# Cloudinary
cloudinary:
  cloud_name: nho
  only_prod: true
  verbose: false
  presets:
    default:
      min_width: 360
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(max-width: 67rem) 90vw, 60rem"
      figure: always
    twothirds:
      min_width: 240
      max_width: 1120
      fallback_max_width: 600
      steps: 5
      sizes: "(max-width: 20rem) 45vw, (max-width: 67rem) 60vw, 40rem"
      figure: always
      attributes:
        class: twothirds
    onehalf:
      min_width: 180
      max_width: 800
      fallback_max_width: 400
      steps: 5
      sizes: "(max-width: 67rem) 45vw, 30rem"
      figure: always
      attributes:
        class: onehalf
    onethird:
      min_width: 120
      max_width: 560
      fallback_max_width: 300
      steps: 5
      sizes: "(max-width: 20rem) 45vw, (max-width: 67rem) 30vw, 20rem"
      figure: always
      attributes:
        class: onethird right
    onefourth:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 5
      sizes: "(max-width: 20rem) 45vw, (max-width: 30rem) 30vw, (max-width: 67rem) 22.5vw, 15rem"
      figure: always
      attributes:
        class: onefourth right
    logo:
      min_width: 120
      max_width: 560
      fallback_max_width: 300
      steps: 5
      sizes: "(max-width: 20rem) 45vw, (max-width: 67rem) 30vw, 20rem"
      figure: never
      attributes:
        class: logo

# Archives
jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archives-year
    month: archives-month
  permalinks:
    year: /:year/
    month: /:year/:month/
